apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: gomate
spec:
  replicas: 1
  restartPolicy: OnFailure
  selector:
    matchLabels:
      app: gomate
  template:
    metadata:
      labels:
        app: gomate
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: modelpv
          persistentVolumeClaim:
            claimName: pretrained-models-volume
        - name: codepv
          persistentVolumeClaim:
            claimName: code-belle-volume
        - emptyDir:
          medium: Memory
          sizeLimit: 1Gi # 适量分配
          name: cache-volume
      containers:
        - name: gomate
          image: registry.ccloud.conestore.cn:8443/chatgpt/torch:v0.0.10
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /model
              name: modelpv
            - mountPath: /code
              name: codepv
            - mountPath: /dev/shm
              name: cache-volume
          resources:
            limits:
              cpu: 4
              nvidia.com/gpu: 4
              memory: "120Gi"
            requests:
              memory: "100Gi"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 8090
              protocol: TCP
          command:
            - "sh"
            - "/code/gomate/start.sh"
